services:
  remnawave-cloudflare-nodes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remnawave-cloudflare-nodes-dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/app/src:ro
      - ./config.yml:/app/config.yml
      - ./hosts.yml:/app/hosts.yml
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - remnawave-cloudflare-nodes

networks:
  remnawave-cloudflare-nodes:
    name: remnawave-cloudflare-nodes
    driver: bridge
